name: script build push

on:
  pull_request:
    types:
      - closed
    branches:
      - desarrollo
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: docker build -t pichonga/hw:${{ github.sha }} .
      
    - name: Login
      run: docker login -u pichonga -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push
      run: docker push pichonga/hw${{ github.sha }}
